export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_ADMIN_PRODUCT_REQUEST = "ALL_ADMIN_PRODUCT_REQUEST";
export const ALL_ADMIN_PRODUCT_SUCCESS = "ALL_ADMIN_PRODUCT_SUCCESS";
export const ALL_ADMIN_PRODUCT_FAIL = "ALL_ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUES" ;
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUES" ;
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET"

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUES" ;
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL"
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET"

export const PRODUCT_DEATILS_REQUEST  = "DEATILS_REQUEST";
export const PRODUCT_DEATILS_SUCCESS  = "DEATILS_SUCCESS";
export const PRODUCT_DEATILS_FAIL =  "DEATILS_FAIL";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUES" ;
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUES" ;
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL"


export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUES" ;
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"





export const CLEAR_ERRORS = "CLEAR";                